-- CreateEnum
CREATE TYPE "SaleStatus" AS ENUM ('CREATED', 'TO_CREATE', 'NONE');

-- AlterTable
ALTER TABLE "Cotizacion" ADD COLUMN     "saleStatus" "SaleStatus" NOT NULL DEFAULT 'NONE';

-- CreateTable
CREATE TABLE "Sale" (
    "id" SERIAL NOT NULL,
    "cotizacionId" INTEGER NOT NULL,
    "customerOrderDate" TIMESTAMP(3),
    "customerOrder" TEXT,
    "line" TEXT,
    "deliveryTime" TEXT,
    "deliveryDate" TIMESTAMP(3),
    "clientInvoiceNumber" TEXT,
    "clientInvoiceDate" TIMESTAMP(3),
    "clientInvoiceDueDate" TIMESTAMP(3),
    "isPaidByClient" BOOLEAN,
    "isPaidByFactoring" BOOLEAN,
    "factoringPaymentAmountUsd" DOUBLE PRECISION,
    "factoringPaymentAmountPen" DOUBLE PRECISION,
    "advanceValueUsdClient" DOUBLE PRECISION,
    "advanceValuePenClient" DOUBLE PRECISION,
    "advancePaymentDate" TIMESTAMP(3),
    "advanceInvoiceNumber" TEXT,
    "advanceInvoiceDate" TIMESTAMP(3),
    "secondPaymentUsdClient" DOUBLE PRECISION,
    "secondPaymentPenClient" DOUBLE PRECISION,
    "secondPaymentDate" TIMESTAMP(3),
    "secondInvoiceNumber" TEXT,
    "secondInvoiceDate" TIMESTAMP(3),
    "thirdPaymentUsdClient" DOUBLE PRECISION,
    "thirdPaymentPenClient" DOUBLE PRECISION,
    "thirdPaymentDate" TIMESTAMP(3),
    "thirdInvoiceNumber" TEXT,
    "thirdInvoiceDate" TIMESTAMP(3),
    "totalSaleUsd" DOUBLE PRECISION,
    "totalSalePen" DOUBLE PRECISION,
    "supplierOrder1" TEXT,
    "advanceValueUsd1" DOUBLE PRECISION,
    "balanceValueUsd1" DOUBLE PRECISION,
    "totalCostUsd1" DOUBLE PRECISION,
    "advanceValuePen1" DOUBLE PRECISION,
    "balanceValuePen1" DOUBLE PRECISION,
    "totalCostPen1" DOUBLE PRECISION,
    "advanceDate1" TIMESTAMP(3),
    "balanceDate1" TIMESTAMP(3),
    "supplierInvoice1" TEXT,
    "balanceInvoice1" TEXT,
    "supplierShipment1" TEXT,
    "invoiceDate1" TIMESTAMP(3),
    "balanceInvoiceDate1" TIMESTAMP(3),
    "shipmentDate1" TIMESTAMP(3),
    "supplierOrder2" TEXT,
    "advanceValueUsd2" DOUBLE PRECISION,
    "balanceValueUsd2" DOUBLE PRECISION,
    "totalCostUsd2" DOUBLE PRECISION,
    "advanceValuePen2" DOUBLE PRECISION,
    "balanceValuePen2" DOUBLE PRECISION,
    "totalCostPen2" DOUBLE PRECISION,
    "advanceDate2" TIMESTAMP(3),
    "balanceDate2" TIMESTAMP(3),
    "supplierInvoice2" TEXT,
    "balanceInvoice2" TEXT,
    "supplierShipment2" TEXT,
    "invoiceDate2" TIMESTAMP(3),
    "balanceInvoiceDate2" TIMESTAMP(3),
    "shipmentDate2" TIMESTAMP(3),
    "supplierOrder3" TEXT,
    "advanceValueUsd3" DOUBLE PRECISION,
    "balanceValueUsd3" DOUBLE PRECISION,
    "totalCostUsd3" DOUBLE PRECISION,
    "advanceValuePen3" DOUBLE PRECISION,
    "balanceValuePen3" DOUBLE PRECISION,
    "totalCostPen3" DOUBLE PRECISION,
    "advanceDate3" TIMESTAMP(3),
    "balanceDate3" TIMESTAMP(3),
    "supplierInvoice3" TEXT,
    "balanceInvoice3" TEXT,
    "supplierShipment3" TEXT,
    "invoiceDate3" TIMESTAMP(3),
    "balanceInvoiceDate3" TIMESTAMP(3),
    "shipmentDate3" TIMESTAMP(3),
    "totalSaleCostUsd" DOUBLE PRECISION,
    "totalSaleCostPen" DOUBLE PRECISION,
    "valueUsd" DOUBLE PRECISION,
    "percentageUsd" DOUBLE PRECISION,
    "valuePen" DOUBLE PRECISION,
    "percentagePen" DOUBLE PRECISION,

    CONSTRAINT "Sale_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Sale_cotizacionId_key" ON "Sale"("cotizacionId");

-- AddForeignKey
ALTER TABLE "Sale" ADD CONSTRAINT "Sale_cotizacionId_fkey" FOREIGN KEY ("cotizacionId") REFERENCES "Cotizacion"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
